name: aquar
description: A new Flutter project.

publish_to: "none"

version: 1.1.0+21

environment:
  sdk: ">=2.18.1 <3.10.3"

dependencies:
  animations: ^2.0.3
  cached_network_image: ^3.2.1
  card_swiper: ^2.0.4
  carousel_slider: ^4.1.1
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^4.0.6
  dotted_border: ^2.0.0+3
  easy_localization: ^3.0.1
  editable: ^2.0.0
  equatable: ^2.0.5
  firebase_core: ^2.7.0
  firebase_dynamic_links: ^5.3.2
  external_app_launcher: ^3.1.0
  firebase_messaging: ^14.2.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_cache_manager: ^3.3.0
  flutter_google_places: ^0.3.0
  flutter_html: null
  flutter_local_notifications: ^12.0.2
  flutter_native_image: ^0.0.6+1
  flutter_phoenix: ^1.0.0
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.8.3
  flutter_share: ^2.0.0
  flutter_svg: ^1.1.5
  flutter_switch: ^0.3.2
  flutter_time_picker_spinner: ^2.0.0
  flutter_widget_from_html: null
  fluttertoast: ^8.0.9
  geocoding: ^2.0.5
  geolocator: ^9.0.2
  get_it: ^7.3.0
  google_maps_flutter: ^2.4.0
  google_maps_flutter_android: ^2.4.14
  google_maps_flutter_platform_interface: ^2.2.6
  google_maps_webservice: ^0.0.19
  image_picker: ^0.8.6
  input_slider: ^0.2.0
  intl: ^0.18.0
  lottie: ^1.3.0
  overlay_support: ^2.0.1
  percent_indicator: ^4.2.2
  pin_code_fields: ^7.4.0
  pin_code_text_field: ^1.8.0
  share_plus: ^7.0.2
  shared_preferences: ^2.0.9
  shimmer: ^2.0.0
  smooth_page_indicator: ^1.0.0+2
  uri_to_file: ^0.2.0
  url_launcher: ^6.1.6
  video_player: ^2.6.1


dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/release_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/translate/
    - assets/lottie/

  fonts:
    - family: Tajawal
      fonts:
        - asset: fonts/Tajawal-Regular.ttf
        - asset: fonts/Tajawal-Bold.ttf
        - asset: fonts/Tajawal-Medium.ttf
