const questionLottie = "assets/lottie/question_lottie.json";
const congratulationLottie = "assets/lottie/congratulation_lottie.json";
const successLottie = "assets/lottie/true_lottie.json";
const logoLottie = "assets/lottie/animation_live3max.json";
// const newLogo = "assets/lottie/mohammed.json";
const newLogo = "assets/lottie/mmmm.json";
// const logoLottie = "assets/lottie/aquar_logo_lottie.json";
const splashLottie = "assets/lottie/splash.json";
// const logoLottie2 = "assets/lottie/White_Friday.json";